apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-800j
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-800j@sha256:9a61bdc753e6d7428a894082e0750e63a3036ecb1555643f00b48929d09a1ebf
        name: my-nodejs
        resources: {}
status: {}
